---
title: "Talks to conferences"
description: |
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## *PAGE UNDER CONSTRUCTION*

List of talks I gave at scientific conferences, including supporting slides (whenever possible).



[11]

Presenter: **Mercier F.**

"Interactive graphics for a better communication on statistical models" - Statistical Methods in Biopharmacy - International meeting, *Paris (France)*, (16-18 Sep 2013)

<div class="contributor_org">
`r xfun::embed_file(here::here("PDFs", "2013 OralPrez SMB.pdf"), text="Download pdf here")`
</div>


[10]

Presenter: Bruno R., Co-presenters: Claret L., **Mercier F.**

"Drug-independent models for predicting overall survival" - ASA Biopharmaceutical Section FDA-Industry Statistics Workshop, *Washington (DC, USA)*, (16-18 Sep 2013)


[09]

Presenter: **Mercier F.** 

"Interactive graphics in pharmaceutical R&D: The right decision" - Strata Europe Conference, *London (UK)*, (11-13 Nov 2013)

<div class="contributor_org">
`r xfun::embed_file(here::here("PDFs", "2013 OralPrez StrataEU.pdf"), text="Download pdf here")`
</div>


[08]

Presenter: **Mercier F.** 

"An adaptive dose-ranging study to fully characterize the dose-response relationship in multiple sclerosis" - Joint BfArM/DIA Statistics Workshop, *Bonn (Germany)*, (17-19 Oct 2012)


[07]

Presenter: **Mercier F.** 

"Model-based drug development in multiple sclerosis: Integrating disease, drug and market data for improved decision making" - Webinar hosted by Pharsight Consulting Services, (12 Sep 2012)


[06]

Presenter: Mandel M., Co-presenters: **Mercier F.**, Eckert B., Chin P., Betensky R.

"Estimating time to disease progression comparing transition models and survival methods" - International Society For Clinical Biostatistics (ISCB) meeting, *Bergen (Norway)*, (19-23 Aug 2012)

<div class="contributor_org">
`r xfun::embed_file(here::here("PDFs", "2012 OralPrez MM ISCB.pdf"), text="Download pdf here")`
</div>


[05]

Presenter: Francis G., Co-presenters: Zhang-Auberson L., deVera A., Looby M., **Mercier F.**, Cohen J.

"Lymphocytes and fingolimod: Temporal pattern and relationship with infections" - Amercian Association of Neurology (AAN) meeting, *Honolulu (HI, USA)*, (13 Apr 2011)

<div class="contributor_org">
`r xfun::embed_file(here::here("PDFs", "2011 OralPrez GF AAN.pdf"), text="Download pdf here")`
</div>


[04]

Presenter: **Mercier F.**, Co-presenter: Pinheiro J.

"Adaptive dose-ranging study in multiple sclerosis" - Design optimization and implementation for adaptive clinical trials - Marcus Evans workshop, *Washington (DC, USA)*, (07 Oct 2010)

<div class="contributor_org">
`r xfun::embed_file(here::here("PDFs", "2010 OralPrez FMJP ADRS MS.pdf"), text="Download pdf here")`
</div>


[03]

Presenter: **Mercier F.**, Co-presenters: Renard D., Looby M., Stansky D.

"Model-based approach for characterizing dose-response of a bronchodilator" - Joint Industry-FDA workshop on Modeling and Simulation, *Cambridge (MA, USA)*, (01 Sep 2010)


[02]

Presenter: **Mercier F.**

"Use of graphics in multidimensional statistical analysis – co-structure of two matrices" - International DIA workshop on Statistical Methodology in Clinical R&D, *Paris (France)*, (10-11 Sep 2003)

<div class="contributor_org">
`r xfun::embed_file(here::here("PDFs", "2003 OralPrez FM DIAstatmeth.pdf"), text="Download pdf here")`
</div>


[01]

Presenter: **Mercier F.**

"Analysis and interpretation of a dose-response clinical study in lipid-lowering therapy" - ISCB meeting, *Dijon (France)*, (08-10 Sep 2002)



<div class="license">
**License and Citation:** You can use, modify, and adapt any of the lessons, but please include the following attribution: 'With permission from Francois Mercier'. 
</div>



